name: db-back-front
services:
  db:
    build: ./db
    environment: 
      MARIADB_DATABASE: 'cats'
      MARIADB_ROOT_PASSWORD: '2025'
    networks:
      - app-network
    ports: 
      - "3306:3306"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on: 
      - "db"
    networks:
      - app-network
    environment:
      NODE_ENV: docker
    ports: 
      - "8080:8080"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      PARCEL_BACKEND_URL: 'http://52.207.238.110:8080'
    ports:
      - "1234:1234"
    networks:
      - app-network
    
networks: 
  app-network: 