name: Build & Ejecutar Pruebas de Integración

on:
  workflow_dispatch:
  pull_request:


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ejecutar pruebas de integración con Docker Compose
        run: docker compose -f ./db/compose.yaml up -d